<div class="custom-acc-aside pull-left">
    <h2 class="acc-title">账户中心</h2>
    <div class="acc-aside-list">
        <a data-toggle="collapse" href="#aside_panel_1" class="collapsed">
            订单中心
        </a>
        <div class="collapse" id="aside_panel_1">
            <ul class="list-unstyled clearfix">
                <li class="active">
                    <a href="#">菜单#1</a>
                </li>
                <li>
                    <a href="#">菜单#2</a>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="account-header clear-fix">
    <div class="col-xs-4 user-info">
        <div class="img">
            <img src="/images/new_icon.png" alt="">
        </div>
        <div class="info">
            <p class="h4 text-ellipsis">您好！
                <span class="name">松江老林</span>
            </p>
            <p class="h4 text-ellipsis">店铺：
                <span class="">阳光汽车后市场</span>
            </p>
            <p class="h4">手机：
                <span>18888888888</span>
            </p>
            <p class="h3">账户金额：￥
                <span class="price">0.00</span>
            </p>
        </div>
    </div>
    <div class="col-xs-4 handle">
        <div class="col-xs-4">
            <img src="/images/new-account/xiugaimima.png" alt="">
            <p class="title">修改密码</p>
        </div>
        <div class="col-xs-4">
            <img src="/images/new-account/dizhiguanli.png" alt="">
            <p class="title">地址管理</p>
        </div>
        <div class="col-xs-4">
            <img src="/images/new-account/zhanghuchongzhi.png" alt="">
            <p class="title">账户充值</p>
        </div>
    </div>
    <div class="col-xs-4 address">
        <p>所属区域：
            <span>北京市北京市辖区朝阳区</span>
        </p>
        <p>默认地址：
            <span>北京市北京市辖区朝阳区</span>
        </p>
        <p>五级区域：
            <span>北京市北京市辖区朝阳区</span>
        </p>
    </div>
</div>
