<!-- ensurance bar -->
<div class="apx-index-new-ensurance container-fluid">
    <div class="container">
        <div class="row text-center">
            <div class="col-xs-3">
                <div class="ensurance_icon icon_1"></div>
                <div class="h3">正品保障</div>
                <p>品质护航 购物无忧</p>
            </div>
            <div class="col-xs-3">
                <div class="ensurance_icon icon_2"></div>
                <div class="h3">极速物流</div>
                <p>极速物流 急速送达</p>
            </div>
            <div class="col-xs-3">
                <div class="ensurance_icon icon_3"></div>
                <div class="h3">无忧售后</div>
                <p>无忧售后 后顾无忧</p>
            </div>
            <div class="col-xs-3">
                <div class="ensurance_icon icon_4"></div>
                <div class="h3">品类丰富</div>
                <p>丰富品类 随心购买</p>
            </div>
        </div>
    </div>
</div>