<div class="global-top-search">
    <div class="container">
        <div class="row">
            <!-- logo -->
            <div class="logo-box hidden">
                <div class="logo-img">
                    <img src="/images/new_icon.png" class="img-responsive">
                </div>
                <div class="h2">九大爷平台</div>
                <p>决策圈俱乐部兄弟品牌</p>
            </div>
            <!-- content -->
            <div class="search-content">
                <!-- search bar -->
                <div class="search-bar">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="精品脚垫">
                        <span class="input-group-btn">
                            <button class="btn" type="button">
                                <i class="glyphicon glyphicon-search"></i>
                            </button>
                        </span>
                    </div>
                    <ul class="list-inline">
                        <li><a href="#" class="actived">新品靠枕</a></li>
                        <li><a href="#">新品靠枕</a></li>
                        <li><a href="#">新品靠枕</a></li>
                        <li><a href="#">新品靠枕</a></li>
                        <li><a href="#">新品靠枕</a></li>
                        <li><a href="#">新品靠枕</a></li>
                        <li><a href="#">新品靠枕</a></li>
                    </ul>
                </div>
                <!-- cart btn -->
                <a href="#" class="btn btn-default btn-cart" data-toggle="popover_cart">
                    <i class="glyphicon glyphicon-shopping-cart"></i> 我的购物车
                    <span class="badge">1</span>
                </a>
            </div>
            <!-- navigation -->
            <div class="search-nav hidden">
                <ul class="list-inline">
                    <li class="actived">
                        <a href="#">首页</a>
                    </li>
                    <li>
                        <a href="#">特供车膜</a>
                    </li>
                </ul>
                <div class="pull-right">
                    <a href="#">
                            <img src="/images/custom/index_new/05-3-广告位.png" alt="">
                        </a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="index-top-nav hidden">
    <div class="logo-box">
        <a href="/">
            <img src="/images/01-1-logo.jpg">
        </a>
    </div>
    <!-- navigation -->
    <div class="search-nav">
        <ul class="list-inline">
            <li class="actived">
                <a href="/">首页</a>
            </li>
            <li>
                <a href="/membrane">特供车膜</a>
            </li>
        </ul>
        <div class="pull-right hidden">
            <a href="#">
                <img src="/images/custom/index_new/05-3-广告位.png" alt="">
            </a>
        </div>
    </div>
</div>
<div class="unindex-other-top-nav">
    <div class="logo-box">
        <a href="/">
            <img src="/images/logo_2.png">
            <img src="/images/yaoniyiqi_img.jpg">
        </a>
    </div>
    <!-- navigation -->
    <div class="search-nav">
        <ul class="list-inline">
            <li class="actived">
                <a href="/">首页</a>
            </li>
            <li>
                <a href="/membrane">特供车膜</a>
            </li>
        </ul>
        <div class="pull-right hidden">
            <a href="#">
                <img src="/images/custom/index_new/05-3-广告位.png" alt="">
            </a>
        </div>
    </div>
</div>
