<nav class="global-top-nav">
    <div class="container">
        <div class="row">
            <ul class="list-inline pull-right">
                <li>
                    您好，请<a href="#">登陆</a>
                    <a class="actived" href="#">我要注册</a>
                </li>
                <li>
                    <a href="#">我的订单</a>
                </li>
                <li>
                    <a href="#">客户服务</a>
                </li>
                <li class="qr">
                    <a href="#">手机端</a>
                    <div class="qr-cnt">
                        <img src="/images/custom/index_new/qrcode-hong.png" class="img-responsive">
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
