<?php
namespace custom\modules\temp\assets;

use common\assets\BaseAssetBundle;

class BlankAsset extends BaseAssetBundle{

    public $sourcePath = '@temp/views/assets';

    public $_js = [
        'js/j.js',
        'js/k.js',
        'js/l.js',
        'js/m.js',
        'js/n.js',
        'js/o.js',
        'js/p.js',
        'js/q.js',
        'js/r.js',
        'js/s.js',
        'js/t.js',
        'js/u.js',
        'js/w.js',
        
        'js/a2.js',
        'js/b2.js',
        'js/c2.js',
        'js/d2.js',
        'js/e2.js',
        'js/f2.js',
        'js/g2.js',
        'js/h2.js',
        'js/i2.js',
        'js/j2.js',
        'js/k2.js',
        'js/l2.js',
        'js/m2.js',
        'js/n2.js',
        'js/o2.js',
        'js/p2.js',
        'js/q2.js',
        'js/r2.js',
        'js/s2.js',
        'js/t2.js',
        'js/u2.js',
        'js/v2.js',
        'js/w2.js',
        'js/x2.js',
        'js/y2.js',
        'js/z2.js',
        'js/djy-user.js',
        'js/djy-order.js',
    ];

    public $_css = [
        'css/j.css',
        'css/k.css',
        'css/l.css',
        'css/m.css',
        'css/n.css',
        'css/o.css',
        'css/p.css',
        'css/q.css',
        'css/r.css',
        'css/s.css',
        'css/t.css',
        'css/w.css',
        'css/a2.css',
        'css/b2.css',
        'css/c2.css',
        'css/d2.css',
        'css/e2.css',
        'css/f2.css',
        'css/g2.css',
        'css/h2.css',
        'css/i2.css',
        'css/j2.css',
        'css/k2.css',
        'css/l2.css',
        'css/m2.css',
        'css/n2.css',
        'css/o2.css',
        'css/p2.css',
        'css/q2.css',
        'css/r2.css',
        'css/s2.css',
        'css/t2.css',
        'css/u2.css',
        'css/v2.css',
        'css/w2.css',
        'css/x2.css',
        'css/y2.css',
        'css/z2.css',
        'css/djy-user.css',
        'css/djy-order.css',
    ];

    public $depends = [
        'custom\assets\GlobalAsset',
    ];
}
