<!-- header start -->
<header class="admin-frame-header">
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <a class="navbar-brand" href="#top">
                <img alt="logo" src="/images/logo_white.png" height="24">
            </a>
        </div>
        <ul class="nav navbar-nav navbar-left">
            <li>管理控制中心</li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li>
                476644346@qq.com
            </li>
            <li>
                <a href="javascript:void(0)">退出</a>
            </li>
        </ul>
    </nav>
</header>
<!-- header end -->
<!-- aside nav start -->
<aside class="admin-frame-aside" id="aside-menu">
    <ul class="nav nav-pills nav-stacked">
        <li class="collapsed" data-parent="#aside-menu" data-toggle="collapse" href="#aside_menu_1">
            <a href="javascript:void(0)">内容一级标题</a>
        </li>
        <li class="collapsed" data-parent="#aside-menu" data-toggle="collapse" href="#aside_menu_2">
            <a href="javascript:void(0)">内容一级标题</a>
        </li>
        <li class="collapsed" data-parent="#aside-menu" data-toggle="collapse" href="#aside_menu_3">
            <a href="javascript:void(0)">内容一级标题</a>
        </li>
    </ul>
    <ul id="aside_menu_1" class="list-unstyled child-list collapse">
        <li class="active"><a href="#">内容内容1</a></li>
        <li><a href="#">内容内容1</a></li>
        <li><a href="#">内容内容1</a></li>
        <li><a href="#">内容内容1</a></li>
        <li><a href="#">内容内容1</a></li>
        <li><a href="#">内容内容1</a></li>
    </ul>
    <ul id="aside_menu_2" class="list-unstyled child-list collapse">
        <li><a href="#">内容内容2</a></li>
        <li><a href="#">内容内容2</a></li>
        <li><a href="#">内容内容2</a></li>
        <li><a href="#">内容内容2</a></li>
        <li><a href="#">内容内容2</a></li>
        <li><a href="#">内容内容2</a></li>
    </ul>
    <ul id="aside_menu_3" class="list-unstyled child-list collapse">
        <li><a href="#">内容内容3</a></li>
        <li><a href="#">内容内容3</a></li>
        <li><a href="#">内容内容3</a></li>
        <li><a href="#">内容内容3</a></li>
        <li><a href="#">内容内容3</a></li>
        <li><a href="#">内容内容3</a></li>
    </ul>
</aside>
<!-- aside nav end -->