<!--[if lt IE 10]>
  <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<nav class="apx-top-nav-army">
    <div class="container">
    	<div class="row">
            <a class="navbar-brand" href="#">
                <img src="/images/index_hk/logo.png" class="img-responsive">
            </a>
            <ul class="list-inline pull-left middle-nav">
                <li class="active"><a href="#">首页</a></li>
                <li><a href="#">特供车膜</a></li>
            </ul>
            <ul class="list-inline pull-right">
                <li>
                    <a href="#">登陆</a>
                </li>
                <li>
                    <a href="#">注册</a>
                </li>
                <li>
                    <a href="#">账户中心</a>
                </li>
                <li>
                    <a href="#" data-toggle="popover_cart"><i class="glyphicon glyphicon-shopping-cart"></i>
                    &nbsp;&nbsp;购物车&nbsp;<strong>0</strong>&nbsp;件</a>
                </li>
            </ul>
        </div>
    </div>
</nav>