<!--[if lt IE 10]>
  <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<nav class="apx-top-nav navbar navbar-default">
    <div class="container">
    	<div class="row">
	        <!-- mobile icon -->
	        <div class="navbar-header">
	            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	                <span class="sr-only">Toggle navigation</span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	            </button>
	        </div>
	        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	        	<div class="row">
		            <ul class="nav navbar-nav navbar-left">
		                <li class="dropdown">
		                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">送至 : 上海 <i class="glyphicon glyphicon-chevron-down"></i></a>
		                    <ul class="dropdown-menu" role="menu">
		                        <li><a href="#">北京</a></li>
		                        <li><a href="#">上海</a></li>
		                        <li><a href="#">广州</a></li>
		                        <li class="divider"></li>
		                        <li><a href="#">blablabla</a></li>
		                    </ul>
		                </li>
		            </ul>
		            <ul class="nav navbar-nav navbar-right with-seperator">
		                <li>
		                    <a href="#">登陆</a>
		                </li>
		                <li>
		                    <a href="#">注册</a>
		                </li>
		                <li>
		                    <a href="#">我的订单</a>
		                </li>
		                <li>
		                    <a href="#">在线服务</a>
		                </li>
		                <li>
		                    <a href="#">帮助中心</a>
		                </li>
		            </ul>
		        </div>
	        </div>
        </div>
    </div>
</nav>