<footer class="apx-footer_seller container">
    <div class="row">
        <ul class="list-inline">
            <li><a href="#">关于APEX</a></li>
            <li><a href="#">合作伙伴</a></li>
            <li><a href="#">营销中心</a></li>
            <li><a href="#">联系客服</a></li>
            <li><a href="#">诚征英才</a></li>
            <li><a href="#">联系我们</a></li>
            <li><a href="#">法律声明</a></li>
        </ul>
    </div>
</footer>
<!-- build:js(src) scripts/vendor.js -->
<!-- bower:js -->
<!-- run `gulp inject` to automatically populate bower script dependencies -->
<!-- endbower -->
<!-- endbuild -->
<!-- build:js({.tmp/serve,.tmp/partials,src}) scripts/index.js -->
<!-- inject:js -->
<!-- js files will be automatically insert here -->
<!-- endinject -->
<!-- inject:partials -->
<!-- angular templates will be automatically converted in js and inserted here -->
<!-- endinject -->
<!-- endbuild -->
</body>

</html>
