<nav class="apx-section-nav navbar navbar-default">
    <div class="container">
        <div class="row">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a data-toggle="collapse" href="#collapseIndexNav"><i class="glyphicon glyphicon-menu-hamburger"></i>所有分类</a>
                </li>
                <li>
                    <a href="#">首页</a>
                </li>
                <li>
                    <a href="#">品牌</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="nav-collapse-container">
        <div class="container">
            <div class="collapse" id="collapseIndexNav">
                <div class="row nav-category">
                    <div class="col-xs-2" data-nav-cate="nav-cate-1"><img src="/images/custom_index/nav1.png">汽车装饰</div>
                    <div class="col-xs-2" data-nav-cate="nav-cate-2"><img src="/images/custom_index/nav2.png">车载电器</div>
                    <div class="col-xs-2" data-nav-cate="nav-cate-3"><img src="/images/custom_index/nav3.png">美容清洗</div>
                    <div class="col-xs-2" data-nav-cate="nav-cate-4"><img src="/images/custom_index/nav4.png">安全自驾</div>
                    <div class="col-xs-2" data-nav-cate="nav-cate-5"><img src="/images/custom_index/nav5.png">维修保养</div>
                    <div class="col-xs-2" data-nav-cate="nav-cate-6"><img src="/images/custom_index/nav6.png">男装/女装</div>
                </div>
            </div>
        </div>
    </div>
    <!--details-->
    <div class="nav-category-detail-container">
        <div class="container">
            <div class="nav-category-detail" id="nav-cate-1">
                <ul class="list-unstyled">
                    <li class="col-xs-4"><a href="#">座垫</a></li>
                    <li class="col-xs-4"><a href="#">脚垫</a></li>
                    <li class="col-xs-4"><a href="#">座套</a></li>
                    <li class="col-xs-4"><a href="#">头枕腰靠枕</a></li>
                    <li class="col-xs-4"><a href="#">车载香膏</a></li>
                </ul>
                <div class="detail-category-hot">
                    <strong class="title">热门推荐</strong>
                    <ul class="list-unstyled">
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="nav-category-detail" id="nav-cate-2">
                <ul class="list-unstyled">
                    <li class="col-xs-4"><a href="#">座垫</a></li>
                    <li class="col-xs-4"><a href="#">脚垫</a></li>
                    <li class="col-xs-4"><a href="#">座套</a></li>
                    <li class="col-xs-4"><a href="#">头枕腰靠枕</a></li>
                    <li class="col-xs-4"><a href="#">车载香膏</a></li>
                </ul>
                <div class="detail-category-hot">
                    <strong class="title">热门推荐</strong>
                    <ul class="list-unstyled">
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="nav-category-detail" id="nav-cate-3">
                <ul class="list-unstyled">
                    <li class="col-xs-4"><a href="#">座垫</a></li>
                    <li class="col-xs-4"><a href="#">脚垫</a></li>
                    <li class="col-xs-4"><a href="#">座套</a></li>
                    <li class="col-xs-4"><a href="#">头枕腰靠枕</a></li>
                    <li class="col-xs-4"><a href="#">车载香膏</a></li>
                </ul>
                <div class="detail-category-hot">
                    <strong class="title">热门推荐</strong>
                    <ul class="list-unstyled">
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="nav-category-detail" id="nav-cate-4">
                <ul class="list-unstyled">
                    <li class="col-xs-4"><a href="#">座垫</a></li>
                    <li class="col-xs-4"><a href="#">脚垫</a></li>
                    <li class="col-xs-4"><a href="#">座套</a></li>
                    <li class="col-xs-4"><a href="#">头枕腰靠枕</a></li>
                    <li class="col-xs-4"><a href="#">车载香膏</a></li>
                </ul>
                <div class="detail-category-hot">
                    <strong class="title">热门推荐</strong>
                    <ul class="list-unstyled">
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="nav-category-detail" id="nav-cate-5">
                <ul class="list-unstyled">
                    <li class="col-xs-4"><a href="#">座垫</a></li>
                    <li class="col-xs-4"><a href="#">脚垫</a></li>
                    <li class="col-xs-4"><a href="#">座套</a></li>
                    <li class="col-xs-4"><a href="#">头枕腰靠枕</a></li>
                    <li class="col-xs-4"><a href="#">车载香膏</a></li>
                </ul>
                <div class="detail-category-hot">
                    <strong class="title">热门推荐</strong>
                    <ul class="list-unstyled">
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="nav-category-detail" id="nav-cate-6">
                <ul class="list-unstyled">
                    <li class="col-xs-4"><a href="#">座垫</a></li>
                    <li class="col-xs-4"><a href="#">脚垫</a></li>
                    <li class="col-xs-4"><a href="#">座套</a></li>
                    <li class="col-xs-4"><a href="#">头枕腰靠枕</a></li>
                    <li class="col-xs-4"><a href="#">车载香膏</a></li>
                </ul>
                <div class="detail-category-hot">
                    <strong class="title">热门推荐</strong>
                    <ul class="list-unstyled">
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <img src="../images/index_section/item1.png">
                                <p>御甲水瓶座</p>
                                <span class="high-lighted">￥2333</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</nav>