<nav class="apx-search-nav navbar navbar-default">
    <div class="container">
        <div class="row">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">
                    <img src="/images/new_icon.png" class="img-responsive">
                </a>
            </div>
            <form class="navbar-form navbar-right" role="search">
                <div class="form-group form-group-lg">
                    <input type="text" class="form-control" placeholder="轮胎，润滑油，车膜">
                    <a type="submit" class="btn btn-default btn-lg">
                        <i class="glyphicon glyphicon-search"></i>
                    </a>
                </div>
                <a href="#" class="btn btn-default btn-lg btn-cart" data-toggle="popover_cart">
                    <i class="glyphicon glyphicon-shopping-cart"></i> 我的购物车
                    <i class="glyphicon glyphicon-chevron-right"></i>
                    <span class="badge">1</span>
                </a>
            </form>
        </div>
    </div>
</nav>
