<div class="apx-seller-aside">
    <a data-toggle="collapse" href="#aside_panel_1">
        <span><img src="/images/seller_menu/menu1.png"></span>交易记录 <i class="glyphicon glyphicon-chevron-down"></i>
    </a>
    <div class="collapse in" id="aside_panel_1">
        <ul class="list-unstyled clearfix">
            <li class="col-xs-6">
                <a href="#">已卖出的商品</a>
            </li>
            <li class="col-xs-6">
                <a href="#">评价管理</a>
            </li>
        </ul>
    </div>
    <a data-toggle="collapse" href="#aside_panel_2">
        <span><img src="/images/seller_menu/menu2.png"></span>物流管理 <i class="glyphicon glyphicon-chevron-down"></i>
    </a>
    <div class="collapse in" id="aside_panel_2">
        <ul class="list-unstyled clearfix">
            <li class="col-xs-6">
                <a href="#">发货</a>
            </li>
            <li class="col-xs-6">
                <a href="#">我要寄快递</a>
            </li>
        </ul>
    </div>
    <a data-toggle="collapse" href="#aside_panel_3">
        <span><img src="/images/seller_menu/menu3.png"></span>宝贝管理 <i class="glyphicon glyphicon-chevron-down"></i>
    </a>
    <div class="collapse in" id="aside_panel_3">
        <ul class="list-unstyled clearfix">
            <li class="col-xs-6">
                <a href="#">出售中的商品</a>
            </li>
            <li class="col-xs-6 actived">
                <a href="#">发布商品</a>
            </li>
        </ul>
    </div>
    <a data-toggle="collapse" href="#aside_panel_4">
        <span><img src="/images/seller_menu/menu4.png"></span>商铺管理 <i class="glyphicon glyphicon-chevron-down"></i>
    </a>
    <div class="collapse in" id="aside_panel_4">
        <ul class="list-unstyled clearfix">
            <li class="col-xs-6">
                <a href="#">查看商铺</a>
            </li>
            <li class="col-xs-6">
                <a href="#">店铺装修</a>
            </li>
        </ul>
    </div>
    <a data-toggle="collapse" href="#aside_panel_5">
        <span><img src="/images/seller_menu/menu5.png"></span>营销中心 <i class="glyphicon glyphicon-chevron-down"></i>
    </a>
    <div class="collapse in" id="aside_panel_5">
        <ul class="list-unstyled clearfix">
            <li class="col-xs-6">
                <a href="#">活动报名</a>
            </li>
            <li class="col-xs-6">
                <a href="#">我要推广</a>
            </li>
        </ul>
    </div>
</div>
