<!-- site map -->
<div class="apx-index-site-map container-fluid">
    <div class="container">
        <div class="qr-section pull-left">
            <img src="/images/logo_white.png" alt="logo" height="50">
            <img src="/images/qr_mockup.png" alt="qr" width="100">
        </div>
        <div class="list-section clearfix">
            <div class="col-xs-3">
                <strong>购物指南</strong>
                <ul>
                    <li><a href="#">导购演示</a></li>
                    <li><a href="#">会员注册</a></li>
                    <li><a href="#">常见问题</a></li>
                    <li><a href="#">客服24小时在线</a></li>
                    <li><a href="#">7天无理由退换货</a></li>
                    <li><a href="#">支付方式</a></li>
                </ul>
            </div>
            <div class="col-xs-3">
                <strong>物流配送</strong>
                <ul>
                    <li><a href="#">免运费政策</a></li>
                    <li><a href="#">签收验货</a></li>
                    <li><a href="#">配送服务承诺</a></li>
                    <li><a href="#">物流查询</a></li>
                    <li><a href="#">海外配送</a></li>
                    <li><a href="#">配送费收取标注</a></li>
                </ul>
            </div>
            <div class="col-xs-3">
                <strong>帮助中心</strong>
                <ul>
                    <li><a href="#">商家进驻</a></li>
                    <li><a href="#">培训中心</a></li>
                    <li><a href="#">广告服务中心</a></li>
                    <li><a href="#">商家帮助</a></li>
                    <li><a href="#">服务市场</a></li>
                    <li><a href="#">退换货政策</a></li>
                </ul>
            </div>
            <div class="col-xs-3">
                <strong>关于我们</strong>
                <ul>
                    <li><a href="#">联系我们</a></li>
                    <li><a href="#">招商加盟</a></li>
                    <li><a href="#">常见问题解决</a></li>
                    <li><a href="#">法律申明</a></li>
                    <li><a href="#">诚聘英才</a></li>
                    <li><a href="#">公司简介</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>